
import React from 'react';
import { VP_GOAL, MAX_MOVEMENT_RANGE, COMMAND_TOWER_COST, COMMAND_TOWER_VP, STARSHIP_CORE_VP_REWARD, ANCIENT_RUIN_VP, STARSHIP_CORE_RESOURCE_COST_TYPE, STARSHIP_CORE_RESOURCE_COST_AMOUNT } from '../constants';
import { ResourceType } from '../types';

const RulebookContent: React.FC = () => {
  return (
    <div className="space-y-4 text-sm">
      <section>
        <h3 className="text-xl font-semibold text-cyan-300 mb-2">Objective</h3>
        <p>Be the first player to achieve {VP_GOAL} Victory Points (VP).</p>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-cyan-300 mb-2">Setup</h3>
        <ul className="list-disc list-inside space-y-1">
          <li>The game is played on a {`7x7`} grid. Most tiles start unexplored.</li>
          <li>Players start at opposite corners with initial resources.</li>
        </ul>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-cyan-300 mb-2">Player Turn</h3>
        <p>On your turn, you perform phases in order:</p>
        <ol className="list-decimal list-inside space-y-1 mt-1">
          <li><strong>Movement Phase:</strong> Move your player piece up to {MAX_MOVEMENT_RANGE} spaces orthogonally (no diagonals) to an adjacent revealed or unrevealed tile. You cannot move through other players.</li>
          <li><strong>Action Phase:</strong> Perform one action from the available options based on your tile.</li>
        </ol>
        <p className="mt-1">After your action, if you control any Command Towers, you gain {COMMAND_TOWER_VP} VP per tower.</p>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-cyan-300 mb-2">Actions</h3>
        <ul className="list-disc list-inside space-y-2">
          <li><strong>Explore (on an Unexplored tile):</strong>
            <ul className="list-disc list-inside ml-4 mt-1">
              <li>The tile is revealed. Its true type and flavor text (generated by AI) are shown.</li>
              <li>If it's a resource node (Scrap Heap, Energy Conduit, Overgrown Sector), immediately gain 1 unit of that resource.</li>
              <li>Other special effects may occur based on tile type (see Tile Types).</li>
            </ul>
          </li>
          <li><strong>Gather (on a revealed resource node):</strong> Gain 1 unit of the resource type of the node.</li>
          <li>
            <strong>Build Outpost (on a Command Tower tile):</strong>
            <ul className="list-disc list-inside ml-4 mt-1">
              <li>Cost: {COMMAND_TOWER_COST[ResourceType.SCRAP]} {ResourceType.SCRAP}, {COMMAND_TOWER_COST[ResourceType.ENERGY]} {ResourceType.ENERGY}.</li>
              <li>Effect: Place your control marker. You gain {COMMAND_TOWER_VP} VP at the end of each of your turns for each Command Tower you control. Only one outpost per Command Tower. If another player builds an outpost, they seize control.</li>
            </ul>
          </li>
          <li>
            <strong>Claim Ancient Tech (on an Ancient Ruin tile, once per ruin):</strong>
            <ul className="list-disc list-inside ml-4 mt-1">
             <li>Effect: Immediately gain {ANCIENT_RUIN_VP} VP and choose to receive 1 free unit of any resource type. This ruin cannot be claimed again by any player.</li>
            </ul>
          </li>
          <li>
            <strong>Investigate Starship Core (on the Starship Core tile, once per player):</strong>
            <ul className="list-disc list-inside ml-4 mt-1">
              <li>Cost: {STARSHIP_CORE_RESOURCE_COST_AMOUNT} {STARSHIP_CORE_RESOURCE_COST_TYPE}. You must have the resource.</li>
              <li>Effect: Immediately gain {STARSHIP_CORE_VP_REWARD} VP. This action can only be performed once per player for the entire game.</li>
            </ul>
          </li>
        </ul>
      </section>
      
      <section>
        <h3 className="text-xl font-semibold text-cyan-300 mb-2">Tile Types</h3>
        <ul className="list-disc list-inside space-y-1">
            <li><strong>Unexplored:</strong> Mystery tile. Use Explore action.</li>
            <li><strong>Empty Space:</strong> No special effect after exploration.</li>
            <li><strong>Scrap Heap:</strong> Source of {ResourceType.SCRAP}.</li>
            <li><strong>Energy Conduit:</strong> Source of {ResourceType.ENERGY}.</li>
            <li><strong>Overgrown Sector:</strong> Source of {ResourceType.BIO_MATTER}.</li>
            <li><strong>Ancient Ruin:</strong> Explore to claim Ancient Tech (VP + free resource).</li>
            <li><strong>Command Tower:</strong> Build an Outpost to gain control and ongoing VP.</li>
            <li><strong>Starship Core:</strong> A high-risk, high-reward location. Investigate for a large VP bonus at a cost.</li>
        </ul>
      </section>

      <section>
        <h3 className="text-xl font-semibold text-cyan-300 mb-2">Winning the Game</h3>
        <p>The first player to reach or exceed {VP_GOAL} VP at any point (even during their turn) immediately wins!</p>
      </section>
    </div>
  );
};

export default RulebookContent;
